<a href="https://colab.research.google.com/github/jarminett/Statistical_Learning_II/blob/main/ForwardPropagation/ForwardPropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**UNIVERSIDAD GALILEO** \\
Instituto de Investigación de Operaciones \\
Posgrado en Análisis y Predicción de Datos \\
Luis Florian, 0710082, sección U \\

**Forward Propagation  y análisis de representaciones intermedias**

- Completar el ejercicio empezado en clase de forward-propagation para los 3 diagramas dados, en el tercer diagrama analizar la representación intermedia(ver descripción detallada en presentación 8). Aplicar operaciones vectorizadas

- Usando markdown agregar una sección indicando cuantos parámetros entrenables se tienen para cada uno de los modelos de la diapositiva "Ejercicio conexiones neuronales (sinapsis)"
Usar como referencia notebook de ejemplo:

https://drive.google.com/file/d/1HCRriuZy_GIngnc4fz4ocXJq3judJbOG/view?usp=sharing

### **Importing Libraries**

In [1]:
import numpy as np

### **Primera Red**

In [5]:
class RN1:
    def __init__(self):
        self.Wc1 = np.array([
            [0.9,0.3,0.2],
            [0.8,0.5,0.4],
            [0.1,0.6,0.7]
        ])
        self. Wc2  = np.array([0.3,0.5,0.9])
    
    def __sigmoid(self,X):
        return 1/(1+np.exp(-X))
    
    def forwardPropagation(self,X):
        A = self.__sigmoid(np.matmul(X,self.Wc1))
        print("First Layer Output:")
        print(A)
        yhat = self.__sigmoid(np.matmul(A,self.Wc2))
        return yhat

In [6]:
# 5 observaciones, 3 variables
x = np.array([
      [1,0,1],
      [1,2,3],
      [4,5,6],
      [7,8,9],
      [10,11,12]
])

red1 = RN1()
y = red1.forwardPropagation(x)


First Layer Output:
[[0.73105858 0.7109495  0.7109495 ]
 [0.94267582 0.95689275 0.95689275]
 [0.99972542 0.99932492 0.99908895]
 [0.99999876 0.99998987 0.99998154]
 [0.99999999 0.99999985 0.99999963]]


### **Segunda Red**

In [7]:
class RN2:
    def __init__(self):
        self.Wc1 = np.array([
            [5, 7 ],
            [-2, -3],
            [-8, 1]
        ])
        self. Wc2  = np.array([7, 5, -6])
    
    def __sigmoid(self,X):
        return 1/(1+np.exp(-X))
    
    def forwardPropagation(self,X):
        X = np.c_[ X, np.ones(X.shape[0]) ] 
        A = self.__sigmoid(np.matmul(X,self.Wc1))
        print("First Intermediate Layer:")
        print(A)
        A = np.c_[ A, np.ones(A.shape[0]) ]  
        yhat = self.__sigmoid(np.matmul(A,self.Wc2.T))
        return yhat

In [9]:
# 5 observaciones, 2 features
X = np.array([
      [0.1,-0.4],
      [1,2],
      [4,8],
      [6,7],
      [8,9]
])

red2 = RN2()
y2 = red2.forwardPropagation(X)

First Intermediate Layer:
[[1.22939862e-03 9.47846437e-01]
 [9.11051194e-04 8.80797078e-01]
 [1.79862100e-02 9.93307149e-01]
 [9.99664650e-01 1.00000000e+00]
 [9.99999168e-01 1.00000000e+00]]


### **Tercera Red**

In [10]:
class RN3:
    def __init__(self):
        self.Wc1 = np.array([
            [0.8, 0.4, 0.3],
            [0.2, 0.9, 0.5]
        ])
        self. Wc2  = np.array([0.3,0.5,0.9])
    
    def __sigmoid(self,X):
        return 1/(1+np.exp(-X))
    
    def forwardPropagation(self,X):
        A = self.__sigmoid(np.matmul(X,self.Wc1))
        print("First Intermediate Layer:")
        print(A)
        yhat = self.__sigmoid(np.matmul(A,self.Wc2))
        return yhat


In [11]:
# 4 observaciones, 2 variables
X = np.array([
      [1,1],
      [1,2],
      [4,5],
      [6,7],
      [8,9]
])

red3 = RN3()
y3= red3.forwardPropagation(X)

First Intermediate Layer:
[[0.73105858 0.78583498 0.68997448]
 [0.76852478 0.90024951 0.78583498]
 [0.98522597 0.99776215 0.97587298]
 [0.99797468 0.99983344 0.9950332 ]
 [0.99972542 0.99998763 0.99899323]]


### **Conclusiones**

* En la primera red existen **3** parámetros entrenables, excluyendo el bias.
* En la segunda red hay **3** parámetros entrenables, los dos pesos y el bias.
* En la tercera red hay **12** parámetros entrenables, excluyendo el bias.